server:
  port: 10086

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shangma?serverTimezone=Asia/Shanghai
    username: root
    password: password

logging:
  level:
    com:
      shangma:
        cn: debug
  file:
    path: C:\\Users\\mqw\\Desktop\\shangma


